version: "3.7"
services:
  ganache:
    container_name: etherbridge-ganache
    image: trufflesuite/ganache:latest
    entrypoint: node /app/dist/node/cli.js -b ${GANACHE_BLOCKTIME} -a 5 --miner.coinbase 0x0E5079117F05C717CF0fEC43ff5C77156395F6E0 -m '${ETHEREUM_MNEMONIC}' --networkId ${GANACHE_NETWORKID} --database.dbPath /ganache_data
    # When there is need to fork actual network
    #  --fork.network rinkeby --fork.blockNumber 11261043
    ports:
      - "${GANACHE_PORT}:8545"
    volumes:
      - "${PWD}/.cache/ganache_data:/ganache_data"

  explorer:
    container_name: etherbridge-explorer
    depends_on:
      - memento
      - ganache
    image: alethio/ethereum-lite-explorer
    ports:
      - "3040:80"
    environment:
      - APP_NODE_URL=http://localhost:${GANACHE_PORT}
      - APP_BASE_URL=http://localhost:3040
    volumes:
      - "${PWD}/.volumes/explorer/config.json:/usr/share/nginx/html/config.json"

  cockroachdb:
    container_name: etherbridge-cockroachdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure --advertise-addr ${DATABASE_HOST}
    ports:
      - "${DATABASE_PORT}:26257"
      - "8080:8080"
    volumes:
      - "${PWD}/.cache/cockroach:/cockroach/cockroach-data"
    environment:
      - COCKROACH_USER=${DATABASE_USER}
      - COCKROACH_PASSWORD=${DATABASE_PASSWORD}
      - COCKROACH_DATABASE=${DATABASE_NAME}

  redis:
    container_name: etherbridge-redis
    image: redis:5.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]

  postgres:
    container_name: etherbridge-postgres
    image: postgres:11.5-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=memento
      - POSTGRES_DB=memento
      - POSTGRES_PASSWORD=memento

  memento:
    container_name: etherbridge-memento
    restart: on-failure
    image: alethio/memento:latest
    depends_on:
      - redis
      - postgres
      - ganache
    ports:
      - 3001:3001
      # - 3000:3000
    environment:
      - PG_PASSWORD=memento
      - PG_USER=memento
    volumes:
      - ${PWD}/.volumes/memento:/config
