# api-related fields
api:
  port: 3001
  dev-cors: true
  dev-cors-host: "*"

# Dashboard-related fields
dashboard:
  port: 3000
  config-management:
    enabled: true

# database fields
db:
  # Database host
  host: "postgres"

  # Database port
  port: 5432

  # Database sslmode
  sslmode: "disable"

  # Database name
  dbname: "memento"

  # Database user (also allowed via PG_USER env var)
  user: "memento"

# ethereum-related fields
eth:
  client:
    http: "http://ganache:8545"
    ws: "ws://ganache:8545"
    poll-interval: "3s"

# feature flags
feature:
  # Backfilling
  backfill:
    enabled: true

  # Lag feature
  lag:
    # Enable/disable the lag feature
    enabled: true
    value: 10

  # Automatic migrations
  automigrate:
    # Enable/disable the automatic migrations
    enabled: true

  # Uncles scraping
  uncles:
    # Enable/disabled the uncles scraping
    enabled: true

# Control what to be logged using format "module=level,module=level"; `*` means all other modules
logging: "*=info"

# redis-related fields
redis:
  # URL of redis server (default:"localhost:6379")
  server: "redis:6379"
  list: "memento-queue"
